### ISSUE TITLE
Issuer badge listing/index

### ISSUE THREAD

**Issue by brianloveswords** [openbadges/openbadges-discussion#1]
## What

A method for an issuer to advertise all of the badge classes they offer.
## Why

With what we have now, it's really hard to build a service that exposes all of the learning/badging opportunities that exist. @thisandagain built [something awesome](https://github.com/thisandagain/badgecrawler) during MozFest that crawls our backpack surfaces all the badge classes we know about, but this only works for badges that have already been earned, and it can't take into account a world of federated backpacks.

If we specify a way for issuers to advertise all of their badges, we (and others!) can then build tools that exposes that data in interesting ways. I also believe this helps us get a little closer to figuring out badge pathways.
## How

Still thinking about this part. Based on some conversations with @thisandagain, @andrewhayward and @toolness here's what I'm thinking
### Advertising the badge index

At the index of the issuer's origin (potentially on other pages as well, e.g. criteria page) there should be a `<meta>` or `<link>` tag with some pointer (HREF) to a file that has the index of all badges.

I am still researching to see whether `<meta>` or `<link>` would be better. Any comments on that would be appreciated.
### Badge Index format

This part could get controversial.
#### JSON

Straightfoward, the file could provide an array of badge classes in JSON format:

``` json
{
  "issuer": {
    "name": "An Example Badge Issuer",
    "image": "https://example.org/logo.png",
    "url": "https://example.org",
    "email": "admin@example.org",
  },
  "badges": [
    {
      "name": "Awesome Robotics Badge",
      "description": "For doing awesome things with robots",
      "image": "https://example.org/robotics-badge.png",
      "criteria": "https://example.org/robotics-badge.html",
      "tags": ["robots", "awesome"],
      "issuer": "https://example.org/organization.json",
    },
    {
      "name": "Rad Pizza Badge",
      "description": "For making amazing pizza",
      "image": "https://example.org/pizza-badge.png",
      "criteria": "https://example.org/pizza-badge.html",
      "tags": ["pizza", "cooking"],
      "issuer": "https://example.org/organization.json",
    }
  ]
}
```
#### RSS/Atom feed

I've also been toying with the idea of providing the badge listing as an RSS/Atom feed. I'm not super experienced with that and I don't if there would be any strong benefits. I'm gonna try to get some RSS experts to contribute to this discussion.

One drawback I can see is that it would potentially increase issuer burden – it's pretty easy to generate the JSON feed, but an RSS feed would take more time and effort, potentially even requiring pulling in additional dependencies. It would also require additional dependencies on the consumer side as well to parse.

I really like being able to use existing standards where they make sense, though, and there are likely some positives that I don't know about.

**Comment by timothyfcook** [comment]
Moving to the archive. https://credmos.com/ has tackled aspects of this.
