### ISSUE TITLE
Re-introduce badge version into standard

### ISSUE THREAD

**Issue by threeqube** [openbadges/openbadges-discussion#12]
As per discussion in https://github.com/mozilla/openbadges-directory/issues/1#issuecomment-36132397 think about badge class versioning:

via @kayaelle "There's really no way to prevent changing the badge class. There's been some discussion of baking the badge class into the badges. That would atleast timestamp the badge data. If the badge class was baked into a badge as well as contain a version - that could inform the directory and save some work. Granted - issuers may not always update their versions but I think a directory would give them incentive to do so. (maybe)."

**Comment by timothyfcook** [comment]
`version` is now a property within the badgeClass: https://github.com/openbadges/openbadges-specification/pull/99/commits/8d26bdb4263bf9f2c3155f6d1ee2adf0a3ff631a

Moving to archive.
