### ISSUE TITLE
Schema Definition for Array Property

### ISSUE THREAD

**Issue by kayaelle** [openbadges/openbadges-discussion#15]
How do you define and validate against an array of values? enum seems to imply that only value can be valid at a time.

What if you want to define an array of strings and more than one can be valid. For instance if we were to define age groupings something like:
"3-5", "6-11", "12-18", "19-40", "40-65", "65-122"

and want to allow multiple values, how to best define that? 

@andrewhayward ? :) 

Thnx

**Comment by timothyfcook** [comment]
Moving to archive.
