### ISSUE TITLE
Summary of proposals made in this venue

### ISSUE THREAD

**Issue by ottonomy** [openbadges/openbadges-discussion#18]
# Suggestions/Issues about the standard listed on the openbadges-discussion repo
## General/about the standard
- [A badge listing/index for an issuer](https://github.com/mozilla/openbadges-discussion/issues/1) -- To list all the learning/badging opportunities that are offered within a system. @brianloveswords suggested a meta (or link) tag to be embedded in the header of the issuer's origin.
- [Allow badges to be "baked" into HTML pages](https://github.com/mozilla/openbadges-discussion/issues/6) @toolness on using a `<link rel="openbadges-assertion" href="badge.json">` to expose machine-readable information about badges described on human-readable webpages. Related to #1.
- [Criteria page markup](https://github.com/mozilla/openbadges-discussion/issues/4) @cmcavoy on how to make criteria pages (which are human-readable HTML) grokkable by applications. An example of a JSON feed. @threeqube comments that there were some previous recommendations to markup criteria page with LRMI. LRMI, which is designed for marking up resources not criteria will not be enough.
- [What is a backpack](https://github.com/mozilla/openbadges-discussion/issues/7) @andrewhayward on defining a possible contract for what could be a backpack.
- [Re-introduce badgeclass version](https://github.com/mozilla/openbadges-discussion/issues/12) @threeqube, @kayaelle and @iamjessklein on indicating what version the badgeclass is, and their relationship to badge templates (a la BadgeKit). Must ensure issuers know how to use this field.
## Identity: Who/what can be a badge earner?
- [Expanding earner identity to include organizations](https://github.com/mozilla/openbadges-discussion/issues/9) @threeqube on trying to make it possible to issue a badge to a company; @xmatthewx suggested LEED certification for a building for example. @iamjessklein on the case of awarding a badge to a book (as in a prize), shouldn't it go to the author?
- We should collect suggestions of other identities people want to issue badges to and write user stories.
## Problems to solve
- [Origin verification](https://github.com/mozilla/openbadges-discussion/issues/10) @ottonomy asks: How can we enforce a same-origin policy in a way that allows smaller projects to still be able to use 3rd party issuing platforms?
## Extensions to the badgeClass
- [Badge JSON file localization](https://github.com/mozilla/openbadges-discussion/issues/2) @brianloveswords & @thisandagain thinking about ways to indicate that a particular badgeclass (or assertion?) is the fr-fr or en version of the same thing.
- [First draft of badgeClass extension spec](https://github.com/mozilla/openbadges-discussion/issues/8) @kayaelle's initial idea on badgeClassExtensions. The thrust of the idea is that issuers use standard ways to add metadatato badges, so that the broader ecosystem can develop tools that understand them. For example, a directory that could sort badges by age range targeted because the issuers included identically structured JSON to indicate that information.
- [JSON-schema extension prototype](https://github.com/mozilla/openbadges-discussion/pull/11) @ottonomy testing some ideas about how to implement @kayaelle's extension idea with JSON-schema: uses an 'extensions' array of JSON objects each with `schema` and `content` objects as properties. 
- [Schema-hash](https://github.com/mozilla/openbadges-discussion/pull/13) @ottonomy trying out introducing a SHA1 hash of the schema to ensure accurate versioning, but it's a little kludgy.
- [Location schema example](https://github.com/mozilla/openbadges-discussion/pull/14) @kayaelle proposing an extension to indicate at what physical or online location a learning experience happens.
- [Age-target schema example](https://github.com/mozilla/openbadges-discussion/issues/15) @kayaelle on an example of an age target extension that enforces selection from a predefined array of age range possibilities.
- [Signed endorsement of a badge class](https://github.com/mozilla/openbadges-discussion/pull/16) @ottonomy proposing a method that organizations who wish to offer an endorsement of a badgeclass could provide the issuer a JSON Web Token signature so that the issuer could include it in the badgeClass extensions.
## Extensions to other stuff?!?!?!
- [Assertion extension](https://github.com/mozilla/openbadges-discussion/pull/17) @ottonomy proposing that a similar extension method could apply to the assertion. The example assertion extensions include a signed endorsement (that this particular earner deserves this particular badge) and embedding some text-based evidence (in this case a poem written by the earner proving they have mad poetry chops.)

**Comment by timothyfcook** [comment]
Moving to archive.
