### ISSUE TITLE
Badge localization

### ISSUE THREAD

**Issue by brianloveswords** [openbadges/openbadges-discussion#2]
From @thisandagain:

As an aside, would now be a good time to think about extending the badge schema? Two items that arose during my experiment were those of geolocation and language specification. For example:

``` json
{
    "name": "MOOC GdP : fondamentaux des projets",
    "description": "A démontré sa connaissance du cours “fondamentaux de la gestion de projet” du MOOC GdP. Voir gestiondeprojet.pm ou http://goo.gl/Hu3GA",
    "image": "https://badge.unow.fr/badges/badge_classique_S1.png",
    "criteria": "https://badge.unow.fr/badges/criteria/22/1b605d6937b8e527cff67d9eb0bd649d",
    "issuer": "https://badge.unow.fr/api/v1/organizations/1-unow-mooc-badges.json",
    "alignment": [],
    "tags": []
}
```

In this instance it would be great to append something like:

``` json
{
    "language": "fr-fr",
    "location": [someLat, someLong]
}
```

This would allow us to easily localize search, and also provide better recommendations for pathways based on user language and locale preferences.

/cc @christi3k

**Comment by timothyfcook** [comment]
Both of these discussions have been addressed in actionable tickets within the Spec repo and have been added to the 2.0 spec! Moving to the archive.
