### ISSUE TITLE
Badge extensions proposal (draft 0.2)

### ISSUE THREAD

**Issue by ottonomy** [openbadges/openbadges-discussion#20]
### Abstract

This proposal shows how additional metadata fields to add more information to a badge could be standardized in an open distributed fashion in keeping with the spirit of the Open Badges Infrastructure.
### The Problem

The [1.0 Open Badges Specifcation](https://github.com/mozilla/openbadges-specification/blob/d14f63c83135543b1d0f98c17cc0cbef74f9fd6d/Assertion/latest.md) allows issuers to include additional metadata fields in the badgeClass JSON, saying "additional properties are allowed if they don't clash with existing properties." Issuers are encouraged to namepace their additions to minimize the risk of two issuers defining differently implemented properties that have the same name. 

This type of freedom makes it impossible to determine how to interpret the additional metadata, and there is no way to tell if two different badges use the same understanding of an additional property that they have included. 

For example, two issuers include a property named "location" in their badge. One provides a URI of a website where someone can sign up for an online course that issues the badge. The other provides a US street address and geolocation of a school that at one time offered a course that issued the badge.
### Discussion

Much of the usefulness of the additional properties, as currently allowed, is assumed to be internal to the issuer, because the implementation of those properties could be closed-source. But many badges might have use for providing more information in a common, machine-readable format. 
### The Proposal

Define an `extensions` array as a property of the badge class, issuer organization, and badge assertion JSON. This is an unordered list of `extensionObjects`, each of which follow a structure like the following example using JSON-schema (JSON-LD, a w3c-track similar structured data specification, is also under consideration):

```
{
    "schema": {
        "reference": "http://example.org/badgeExtension1v1.json",
        "hash": "sha1$cf23df2207d99a74fbe169e3eba035e633b65d94"
    },
    "content": {
        "extensionProperty": "some text"
    }
}
```

The proposal also requires an extension definition file to be accessible at the schema.reference URL (JSON-schema). In this case, it would define that the extension content could (or must) have a property called `extensionProperty` whose content would be text. The issuer generates a sha1 hash of the json retrieved from that location and includes it in the referrer object following the format `alg$hash`. This allows applications dealing in extended badges to cache them and determine if schema have changed, or if schema referenced at different locations are identical.
### Consequences

**Backwards Compatibility:** The proposal is backwards compatible with the 1.0 assertion specification for the badgeClass. It is ambiguous if it is compatible with the assertion or the issuer organization, though the addition does not conflict with any existing property. If an application analyzing the extended badge does not know how to understand the extensions array, it should ignore and leave them intact.

**Standardized extension formats allow multiple issuers to define additional metadata in common**, so that badge consumers can better understand...
    1. What the additional information means to the issuer in terms of what fields are available and/or required as well as the data types that could populate those fields.
    2. Whether two different badges are using the same definition for an additional property as each other.
    3. Whether a badge extension is properly formed according to its definition.
### Request for Comment and Code
- We are interested in fleshing out the JSON-schema examples, including applications that verify example badge objects against their schema. Look through the [pull requests](https://github.com/mozilla/openbadges-discussion/pulls) in this repository for some ideas of how extensions could be used.

**Comment by timothyfcook** [comment]
Moving to archive.
