### ISSUE TITLE
which fields are truly mandatory (or which validator is truly reliable)?

### ISSUE THREAD

**Issue by 1l2p** [openbadges/openbadges-discussion#22]
We created a few test JSON that are missing some of the fields that are marked as mandatory in the specifications (e.g. uid), but the validator at http://validator.openbadges.org/ considered them valid. 

Are the specifications out of date or is the validator not validating accurately (or am I missing something, always a possibility)?

**Comment by ottonomy** [comment]
@1l2p Indeed the validator has issues, and often the result of that is that badges that should not be valid are accepted. I didn't think uid was one of the fields that encountered that error, but if you could post the JSON you're using, I could dig into it and figure out exactly why.

**Comment by timothyfcook** [comment]
Validator has been updated. Moving to archive.
