### ISSUE TITLE
Criteria page markup

### ISSUE THREAD

**Issue by cmcavoy** [openbadges/openbadges-discussion#4]
An `issuer-client` (indexer is the most obvious, there's probably more) needs to be able to grab some key information about a `badgeClass` that goes beyond the base specification:
- How to earn the badge
- A rubric that an assessor would use to assess completion of the criteria
- Time to earn
- Relation to other badges (prerequisites, placement on a learning pathway)
- Age range / skill level / prerequisite skills

[OBr](mozilla/openbadger) provides a lot of the above in the `/v2/program/[shortname]` feed, an example (the Mozilla Summit Toronto badge):

```
"mozilla-summiteer-2013-toronto": {

    "name": "Mozilla Summiteer 2013: Toronto",
    "shortname": "mozilla-summiteer-2013-toronto",
    "description": "The Mozilla Summiteer badge acknowledges attendance and participation at the Mozilla Summit 2013 in Toronto, Ontario.",
    "prerequisites": [ ],
    "image": "http://badger.openbadges.org/badge/image/mozilla-summiteer-2013-toronto.png",
    "criteria": "The Summiteer badge is a special edition badge created to acknowledge attendance at the 2013 Mozilla Summit. It is earned by working and sharing among peers at any one of three Summit locales—Santa Clara, Toronto, Brussels—during the 2013 Mozilla Summit.\r\n\r\nThis badge was earned at the 2013 Mozilla Summit in Toronto, Ontario, Canada.",
    "tags": [
        "attendance"
    ],
    "categories": [ ],
    "ageRange": [ ],
    "rubric": {
        "items": [
            {
                "text": "Satisfies the following criteria:\nThe Summiteer badge is a special edition badge created to acknowledge attendance at the 2013 Mozilla Summit. It is earned by working and sharing among peers at any one of three Summit locales—Santa Clara, Toronto, Brussels—during the 2013 Mozilla Summit.\r\n\r\nThis badge was earned at the 2013 Mozilla Summit in Toronto, Ontario, Canada.",
                "required": true
            }
        ]
    },
    "program": "1e4f3689c245070f39febe7f39ad4ede40e44c0e"

},
```

We want to preserve criteria pages as html, so they can continue to look cool...so the standard should probably be either RDFa, microformat, or something new and shiny I've never heard of.

**Comment by timothyfcook** [comment]
Moving to archive.

Criteria are now embedded into the badgeClass https://github.com/openbadges/openbadges-specification/pull/99
