### ISSUE TITLE
What is a Backpack?

### ISSUE THREAD

**Issue by andrewhayward** [openbadges/openbadges-discussion#7]
At some point soon we're going to need to define what makes a backpack. I'm sure @stenington knows a lot more about this than I do, but I'll make a start.

Right now, our backpack boils down to three things:
- Users
- Badges
- Collections

Obviously users and badges are first-order entities (duh), but do we want to specify collections at the same level? My gut feeling is yes, but would be good to get other people's thoughts on the matter.

So, from a Open Badges Backpack (OBb) specification point of view, this might be considered a reasonable start ([RFC 2119](http://www.ietf.org/rfc/rfc2119.txt) yadda yadda):
- **An OBb _must_ have "user accounts"** (loosely defined)
- **An OBb _must_ allow users to add badges**
- An OBb _may_ allow users to make specific badges "public"
- An OBb _should_ allow users to create collections of badges
- An OBb _may_ allow users to make specific collections "public"

"Public" here depends on context, and doesn't necessarily mean 'available to the whole world'. Within a school, for example, making your badge "public" may well still restrict it to people within the confines of the school network.

Further to these basic requirements, we probably also want to go a bit further (to cover stuff like federation, @brianloveswords?), and say that an OBb _must_ have a way of programmatically interfacing with data (an API):
- An OBb API _may_ allow a client to create, delete and update users
- **An OBb API _must_ allow a client to add a badge for a user**
- An OBb API _should_ allow a client to delete a badge for a user
- An OBb API _should_ allow a client to retrieve a user's badges
- An OBb API _may_ allow a client to make a user's badge public (or not)
- An OBb API _should_ allow a client to create, delete and update a collection for a user
- An OBb API _should_ allow a client to retrieve a user's collections
- An OBb API _should_ allow a client to add/remove a badge to/from a user's collection
- An OBb API _may_ allow a client to make a user's collection public (or not)

Of course, all of these actions _should_ (_must_?) be restricted by permissions of varying levels, yet to be discussed. The only required point here is the ability to push badges to a backpack, meaning a full-blown API is not actually necessary for standard compliance.

Anyway, thoughts?

**Comment by timothyfcook** [comment]
Moving to archive.
