### ISSUE TITLE
Suggestion to Experiment with Extending the BadgeClass

### ISSUE THREAD

**Issue by kayaelle** [openbadges/openbadges-discussion#8]
I'd like to propose a suggestion on extending the BadgeClass to allow for additional data. Here's an example of how to do this:

``` json
{
  "name": "Awesome Robotics Badge",
  "description": "For doing awesome things with robots that people think is pretty great.",
  "image": "https://example.org/robotics-badge.png",
  "criteria": "https://example.org/robotics-badge.html",
  "tags": ["robots","awesome"],
  "issuer": "https://example.org/organization.json",
  "alignment": [
    {
      "name": "CCSS.ELA-Literacy.RST.11-12.3",
      "url": "http://www.corestandards.org/ELA-Literacy/RST/11-12/3",
      "description": "Follow precisely a complex multistep procedure when carrying out experiments, taking measurements, or performing technical tasks; analyze the specific results based on explanations in the text."
    },
    {
      "name": "CCSS.ELA-Literacy.RST.11-12.9",
      "url": "http://www.corestandards.org/ELA-Literacy/RST/11-12/9",
      "description": " Synthesize information from a range of sources (e.g., texts, experiments, simulations) into a coherent understanding of a process, phenomenon, or concept, resolving conflicting information when possible."
    }
  ],
  "badgeClassExtensions": [
    {
      "badgeSpecification": {
        "reference": "http://url-to-spec",
        "version": "0.5"
      },
      "age": "K-12",
      "categories": ["Education","Technology"],
      "location": {
        "url": "http://online-course",
        "streetAddress": "123 test rd",
        "city": "providence",
        "stateProvince": "RI",
        "zipPostal": "02903"
      }
    },
    {
      "badgeSpecification": {
        "reference": "http://url-to-spec2",
        "version": "0.7"
      },
      "cost": "50.00"
    }
  ]
}
```

The badgeClassExtensions property could allow for a single or multiple specs to be referenced. The specs properties would only be an extension of the defined BadgeClass in the Assertion spec which would continue to be the common properties that all badges continue to use.

Ideally the community would adopt specs based on their industry in which they can define their needed properties and decision making process. Can envision some specs being more formal than others. Backpacks could decide which specs they use.

The above example doesn't have true spec properties included nor does it explain how the spec reference would be provided programatically (vs just a url with text explaining the property definitions). It's an example of how the BadgeClass could be extended to allow for more data, flexibility while maintaining a standard for all open badges.

Not suggesting at this point that the Assertion spec be changed to allow this just yet. Thinking that after some discussion here, broadening the discussion to the overall community, thinking through guidelines spec definitions and then creating a spec leaning with feedback from the learning community. Then test the waters to see if there's adoption, iterate on the spec and continue discussion on the data that can connect open badges.

Thoughts?

**Comment by timothyfcook** [comment]
Moving to archive. Extensions are real!
