### ISSUE TITLE
Explore issuing badges to a non-human entity like an org or a book etc

### ISSUE THREAD

**Issue by threeqube** [openbadges/openbadges-discussion#9]
On multiple occasions it has been brought up whether a badge could be issued to an organization or non-human entity. Some examples are as follows:
- Greenpeace gives an organization like Toyota a badge for cutting down carbon admissions and declaring to only build hybrids and electric cars
- New York Times gives the book (ok, it can be given to author as well I suppose) a "NYTimes bestseller" badge

The hack solution based on existing standard is to just issue the org or book a badge via an email but might be worthy of a deeper discussion to explore alternatives.

**Comment by timothyfcook** [comment]
You can now endorse badgeClasses which, in a way, is like endorsing the owner of that badgeClass. 

You can now issue badgeAssertions to multiple identity types: https://github.com/openbadges/openbadges-specification/issues/77

Moving to archive.
